# Generated by Django 5.1.1 on 2025-07-16 00:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_profile_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='settings_theme',
            field=models.CharField(choices=[('light', 'Light'), ('dark', 'Dark')], default='dark', max_length=50),
        ),
    ]
