# Generated by Django 5.1.1 on 2025-07-16 00:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='serversetting',
            name='system_name',
            field=models.CharField(default='Zeo ERP', max_length=255),
        ),
    ]
