# Generated by Django 5.1.1 on 2025-07-29 20:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_serversetting_re_lead_form_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='serversetting',
            name='re_lead_form',
        ),
        migrations.RemoveField(
            model_name='serversetting',
            name='roofing_lead_form',
        ),
        migrations.RemoveField(
            model_name='serversetting',
            name='solar_lead_form',
        ),
    ]
