# Generated by Django 5.1.1 on 2025-07-29 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_remove_serversetting_re_lead_form_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='serversetting',
            name='re_lead_form',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='serversetting',
            name='roofing_lead_form',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='serversetting',
            name='solar_lead_form',
            field=models.BooleanField(default=True),
        ),
    ]
