# Generated by Django 5.1.1 on 2025-11-24 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_opportunity'),
    ]

    operations = [
        migrations.AddField(
            model_name='opportunity',
            name='pipeline_type',
            field=models.CharField(choices=[('wholesaling', 'Wholesaling'), ('land', 'Land'), ('longterm', 'Long Term')], default='wholesaling', max_length=50),
        ),
    ]
