# Generated by Django 5.1.1 on 2025-11-25 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_opportunity_pipeline_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='opportunity',
            name='stage',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='opportunity',
            name='pipeline_type',
            field=models.CharField(choices=[('wholesaling', 'Wholesaling'), ('land', 'Land'), ('longterm', 'Long-Term'), ('new_leads', 'New Leads')], default='wholesaling', max_length=50),
        ),
    ]
