# Generated by Django 5.1.1 on 2025-11-25 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_opportunity_stage_alter_opportunity_pipeline_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='serversetting',
            name='geo_api_key',
            field=models.CharField(blank=True, help_text='API Key for Geocoding services', max_length=255, null=True),
        ),
    ]
