# Generated by Django 5.1.1 on 2025-07-29 20:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0007_role_created_at_role_updated_at'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Platform',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(blank=True, max_length=50, null=True)),
                ('source_type', models.CharField(blank=True, choices=[('voip_dialer', 'VoIP Dialer'), ('sms_platform', 'Text Messaging'), ('crm', 'CRM'), ('data_provider', 'Data Source'), ('email_marketing', 'Email Marketing'), ('automation_tool', 'Automation Tool'), ('admin_platform', 'Admin Platform')], max_length=50, null=True)),
                ('active', models.BooleanField(default=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Campaign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(blank=True, max_length=50, null=True)),
                ('agents_count', models.PositiveIntegerField(default=0)),
                ('daily_leads', models.PositiveIntegerField(default=0)),
                ('campaign_type', models.CharField(blank=True, choices=[('calling', 'Calling Service'), ('texting', 'Texting Service'), ('email', 'Email Service'), ('admin', 'Admin Service'), ('marketing', 'Marketing Service'), ('sales', 'Sales Service')], max_length=50, null=True)),
                ('lead_points', models.PositiveIntegerField(default=0)),
                ('documentation', models.TextField(blank=True, null=True)),
                ('qa_sop', models.TextField(blank=True, null=True)),
                ('status', models.CharField(blank=True, choices=[('active', 'Active'), ('hold', 'Hold'), ('pending', 'Pending'), ('inactive', 'Inactive')], default='active', max_length=50, null=True)),
                ('active', models.BooleanField(default=True)),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.profile')),
                ('platforms', models.ManyToManyField(blank=True, related_name='platform_campaign', to='campaigns.platform')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Lead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('handled', models.DateTimeField(blank=True, null=True)),
                ('property_type', models.CharField(blank=True, choices=[('house', 'House'), ('vacant_land', 'Vacant Land'), ('business', 'Business'), ('apartment', 'Apartment'), ('condo', 'Condo'), ('mobile_home', 'Mobile Home')], default='house', max_length=50, null=True)),
                ('name', models.CharField(blank=True, max_length=50, null=True)),
                ('phone', models.CharField(blank=True, max_length=50, null=True)),
                ('email', models.CharField(blank=True, max_length=50, null=True)),
                ('timeline', models.CharField(blank=True, choices=[('two_weeks', '2 Weeks'), ('one_month', '1 Month'), ('two_months', '2 Months'), ('three_months', '3 Months'), ('four_months', '4 Months'), ('five_months', '5 Months'), ('six_months', '6 Months'), ('6_plus_months', '6+ Months')], default='two_weeks', max_length=50, null=True)),
                ('reason', models.TextField(blank=True, null=True)),
                ('property_address', models.TextField(blank=True, null=True)),
                ('asking_price', models.CharField(blank=True, max_length=50, null=True)),
                ('market_value', models.CharField(blank=True, max_length=50, null=True)),
                ('general_info', models.TextField(blank=True, null=True)),
                ('property_url', models.TextField(blank=True, null=True)),
                ('callback', models.CharField(blank=True, max_length=50, null=True)),
                ('extra_notes', models.TextField(blank=True, null=True)),
                ('roof_age', models.CharField(blank=True, max_length=50, null=True)),
                ('appointment_time', models.CharField(blank=True, max_length=50, null=True)),
                ('known_issues', models.TextField(blank=True, null=True)),
                ('state', models.CharField(blank=True, default=0, max_length=50, null=True)),
                ('county', models.CharField(blank=True, default=0, max_length=50, null=True)),
                ('latitude', models.FloatField(blank=True, default=0, null=True)),
                ('longitude', models.FloatField(blank=True, default=0, null=True)),
                ('status', models.CharField(blank=True, choices=[('pending', 'Pending'), ('qualified', 'Qualified'), ('disqualified', 'Disqualified'), ('callback', 'Callback'), ('duplicated', 'Duplicated')], default='pending', max_length=50, null=True)),
                ('quality_notes', models.TextField(blank=True, null=True)),
                ('quality_to_agent_notes', models.TextField(blank=True, null=True)),
                ('assigned_time', models.DateTimeField(blank=True, null=True)),
                ('fireback', models.BooleanField(default=False)),
                ('handling_time', models.DurationField(blank=True, null=True)),
                ('lead_flow', models.FloatField(blank=True, default=0, null=True)),
                ('lead_flow_json', models.JSONField(blank=True, default=dict, null=True)),
                ('active', models.BooleanField(default=True)),
                ('agent_profile', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lead_profile', to='users.profile')),
                ('agent_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('assigned', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_profile', to='users.profile')),
                ('campaign', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lead_campaign', to='campaigns.campaign')),
                ('handled_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='handled_by_lead_post', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
