# Generated by Django 5.1.1 on 2025-07-29 20:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0002_rename_state_lead_states'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lead',
            old_name='states',
            new_name='state',
        ),
    ]
