# Generated by Django 5.1.1 on 2025-07-29 20:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0003_rename_states_lead_state'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Lead',
        ),
    ]
