# Generated by Django 5.1.1 on 2025-08-01 17:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0005_lead'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AlterField(
            model_name='lead',
            name='timeline',
            field=models.CharField(blank=True, choices=[('two_weeks', '2 Weeks'), ('one_month', '1 Month'), ('two_months', '2 Months'), ('three_months', '3 Months'), ('four_months', '4 Months'), ('five_months', '5 Months'), ('six_months', '6 Months'), ('six_plus_months', '6+ Months')], default='two_weeks', max_length=50, null=True),
        ),
        migrations.CreateModel(
            name='CustomFormField',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=255)),
                ('field_type', models.CharField(choices=[('text', 'Text'), ('number', 'Number'), ('email', 'Email'), ('date', 'Date'), ('boolean', 'Checkbox'), ('select', 'Select'), ('textarea', 'Textarea')], max_length=50)),
                ('required', models.BooleanField(default=False)),
                ('order', models.PositiveIntegerField(default=0)),
                ('options', models.JSONField(blank=True, null=True)),
                ('form', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fields', to='campaigns.customform')),
            ],
        ),
    ]
