# Generated by Django 5.1.1 on 2025-08-01 17:56

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0006_customform_alter_lead_timeline_customformfield'),
    ]

    operations = [
        migrations.AddField(
            model_name='customform',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='customform',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='customformfield',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='customformfield',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='customformfield',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
