# Generated by Django 5.1.1 on 2025-08-04 17:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0007_customform_active_customform_updated_at_and_more'),
        ('users', '0007_role_created_at_role_updated_at'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lead',
            old_name='extra_notes',
            new_name='general_notes',
        ),
        migrations.RemoveField(
            model_name='lead',
            name='agent_profile',
        ),
        migrations.RemoveField(
            model_name='lead',
            name='agent_user',
        ),
        migrations.RemoveField(
            model_name='lead',
            name='appointment_time',
        ),
        migrations.RemoveField(
            model_name='lead',
            name='asking_price',
        ),
        migrations.RemoveField(
            model_name='lead',
            name='callback',
        ),
        migrations.RemoveField(
            model_name='lead',
            name='county',
        ),
        migrations.RemoveField(
            model_name='lead',
            name='general_info',
        ),
        migrations.RemoveField(
            model_name='lead',
            name='known_issues',
        ),
        migrations.RemoveField(
            model_name='lead',
            name='latitude',
        ),
        migrations.RemoveField(
            model_name='lead',
            name='lead_flow',
        ),
        migrations.RemoveField(
            model_name='lead',
            name='lead_flow_json',
        ),
        migrations.RemoveField(
            model_name='lead',
            name='longitude',
        ),
        migrations.RemoveField(
            model_name='lead',
            name='market_value',
        ),
        migrations.RemoveField(
            model_name='lead',
            name='property_address',
        ),
        migrations.RemoveField(
            model_name='lead',
            name='property_type',
        ),
        migrations.RemoveField(
            model_name='lead',
            name='property_url',
        ),
        migrations.RemoveField(
            model_name='lead',
            name='reason',
        ),
        migrations.RemoveField(
            model_name='lead',
            name='roof_age',
        ),
        migrations.RemoveField(
            model_name='lead',
            name='state',
        ),
        migrations.RemoveField(
            model_name='lead',
            name='timeline',
        ),
        migrations.AddField(
            model_name='lead',
            name='agent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.profile'),
        ),
        migrations.AddField(
            model_name='lead',
            name='lead_type',
            field=models.CharField(blank=True, choices=[('real_estate', 'Real Estate'), ('roofing', 'Roofing'), ('custom', 'Custom')], max_length=50, null=True),
        ),
        migrations.CreateModel(
            name='CustomLead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.JSONField()),
                ('active', models.BooleanField(default=True)),
                ('form', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='campaigns.customform')),
                ('lead', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='customlead_info', to='campaigns.lead')),
            ],
        ),
        migrations.CreateModel(
            name='RealEstateLead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('property_type', models.CharField(blank=True, choices=[('house', 'House'), ('vacant_land', 'Vacant Land'), ('business', 'Business'), ('apartment', 'Apartment'), ('condo', 'Condo'), ('mobile_home', 'Mobile Home')], default='house', max_length=50, null=True)),
                ('timeline', models.CharField(blank=True, choices=[('two_weeks', '2 Weeks'), ('one_month', '1 Month'), ('two_months', '2 Months'), ('three_months', '3 Months'), ('four_months', '4 Months'), ('five_months', '5 Months'), ('six_months', '6 Months'), ('six_plus_months', '6+ Months')], default='two_weeks', max_length=50, null=True)),
                ('reason', models.TextField(blank=True, null=True)),
                ('property_address', models.TextField(blank=True, null=True)),
                ('asking_price', models.CharField(blank=True, max_length=50, null=True)),
                ('market_value', models.CharField(blank=True, max_length=50, null=True)),
                ('property_url', models.TextField(blank=True, null=True)),
                ('callback', models.CharField(blank=True, max_length=50, null=True)),
                ('active', models.BooleanField(default=True)),
                ('lead', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='realestate_info', to='campaigns.lead')),
            ],
        ),
        migrations.CreateModel(
            name='RoofingLead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('property_type', models.CharField(blank=True, choices=[('house', 'House'), ('vacant_land', 'Vacant Land'), ('business', 'Business'), ('apartment', 'Apartment'), ('condo', 'Condo'), ('mobile_home', 'Mobile Home')], default='house', max_length=50, null=True)),
                ('property_address', models.TextField(blank=True, null=True)),
                ('roof_age', models.CharField(blank=True, max_length=50, null=True)),
                ('appointment_time', models.CharField(blank=True, max_length=50, null=True)),
                ('active', models.BooleanField(default=True)),
                ('lead', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='roofing_info', to='campaigns.lead')),
            ],
        ),
    ]
