# Generated by Django 5.1.1 on 2025-10-22 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0008_rename_extra_notes_lead_general_notes_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lead',
            name='general_notes',
        ),
        migrations.AddField(
            model_name='realestatelead',
            name='general_notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='roofinglead',
            name='general_notes',
            field=models.TextField(blank=True, null=True),
        ),
    ]
